return function(colors)
    return {
        SnacksNotifierDebug = { link = "NormalFloat" },
        SnacksNotifierBorderDebug = { link = "FloatBorder" },
        SnacksNotifierIconDebug = { link = "Comment" },
        SnacksNotifierTitleDebug = { link = "Comment" },
        SnacksNotifierError = { link = "NormalFloat" },
        SnacksNotifierBorderError = { link = "DiagnosticError" },
        SnacksNotifierIconError = { link = "DiagnosticError" },
        SnacksNotifierTitleError = { link = "DiagnosticError" },
        SnacksNotifierInfo = { link = "NormalFloat" },
        SnacksNotifierBorderInfo = { link = "DiagnosticInfo" },
        SnacksNotifierIconInfo = { link = "DiagnosticInfo" },
        SnacksNotifierTitleInfo = { link = "DiagnosticInfo" },
        SnacksNotifierTrace = { link = "NormalFloat" },
        SnacksNotifierBorderTrace = { fg = colors.violet },
        SnacksNotifierIconTrace = { fg = colors.violet },
        SnacksNotifierTitleTrace = { fg = colors.violet },
        SnacksNotifierWarn = { link = "NormalFloat" },
        SnacksNotifierBorderWarn = { link = "DiagnosticWarn" },
        SnacksNotifierIconWarn = { link = "DiagnosticWarn" },
        SnacksNotifierTitleWarn = { link = "DiagnosticWarn" },
        SnacksDashboardDesc = { fg = colors.foreground },
        SnacksDashboardFooter = { fg = colors.comment },
        SnacksDashboardHeader = { fg = colors.blue },
        SnacksDashboardIcon = { fg = colors.comment },
        SnacksDashboardKey = { fg = colors.target, bold = true },
        SnacksDashboardSpecial = { fg = colors.purple },
        SnacksDashboardDir = { fg = colors.inconspicuous },
        SnacksIndent = { fg = colors.inconspicuous, nocombine = true },
        SnacksIndentScope = { fg = colors.splitline, nocombine = true },
        SnacksInputBorder = { link = "FloatBorder" },
        SnacksInputTitle = { link = "FloatTitle" },
        SnacksPickerInputBorder = { link = "FloatBorder" },
        SnacksPickerInputTitle = { link = "FloatTitle" },
        SnacksPickerBoxTitle = { link = "FloatTitle" },
        SnacksPickerMatch = { fg = colors.match },
        SnacksPickerSelected = { bg = colors.selection },
        SnacksPickerDirectory = { link = "Directory" },
        SnacksPickerDir = { fg = colors.comment },
        SnacksPickerFile = { fg = colors.foreground },
    }
end
