return function(colors)
    return {
        TodoFgFIX = { fg = colors.red },
        TodoBgFIX = { fg = colors.background, bg = colors.red, bold = true },
        TodoSignFIX = { fg = colors.red },
        TodoFgTODO = { fg = colors.blue },
        TodoBgTODO = { fg = colors.background, bg = colors.blue, bold = true },
        TodoSignTODO = { fg = colors.blue },
        TodoFgHACK = { fg = colors.yellow },
        TodoBgHACK = { fg = colors.background, bg = colors.yellow, bold = true },
        TodoSignHACK = { fg = colors.yellow },
        TodoFgWARN = { fg = colors.yellow },
        TodoBgWARN = { fg = colors.background, bg = colors.yellow, bold = true },
        TodoSignWARN = { fg = colors.yellow },
        TodoFgPERF = { fg = colors.purple },
        TodoBgPERF = { fg = colors.background, bg = colors.purple, bold = true },
        TodoSignPERF = { fg = colors.purple },
        TodoFgNOTE = { fg = colors.teal },
        TodoBgNOTE = { fg = colors.background, bg = colors.teal, bold = true },
        TodoSignNOTE = { fg = colors.teal },
        TodoFgTEST = { fg = colors.violet },
        TodoBgTEST = { fg = colors.background, bg = colors.violet, bold = true },
        TodoSignTEST = { fg = colors.violet },
    }
end
