local M = {}

M.get = function()
    local colors = require("nova.colors").get()

    -- stylua: ignore
    return {
        ColorColumn    = { bg = colors.stripline },
        Conceal        = { bg = colors.inconspicuous },
        Cursor         = { fg = colors.red },
        lCursor        = { fg = colors.red },
        CursorIM       = { fg = colors.red },
        CursorColumn   = { bg = colors.stripline },
        CursorLine     = { bg = colors.stripline },
        Directory      = { fg = colors.blue },
        DiffAdd        = { fg = colors.green, bg = colors.stripline },
        DiffChange     = { fg = colors.blue, bg = colors.stripline },
        DiffDelete     = { fg = colors.red, bg = colors.stripline },
        DiffText       = { fg = colors.red, bg = colors.stripline },
        EndOfBuffer    = { fg = colors.inconspicuous },
        TermCursor     = { fg = colors.red },
        TermCursorNC   = { fg = colors.inconspicuous },
        ErrorMsg       = { fg = colors.red },
        VertSplit      = { fg = colors.splitline },
        WinSeparator   = { fg = colors.splitline },
        FloatBorder    = { fg = colors.splitline },
        Folded         = { fg = colors.selection },
        FoldColumn     = { fg = colors.selection },
        SignColumn     = { fg = colors.blue },
        IncSearch      = { fg = colors.lime, reverse = true },
        Substitute     = { fg = colors.lime, reverse = true },
        LineNr         = { fg = colors.inconspicuous },
        LineNrAbove    = { fg = colors.inconspicuous },
        LineNrBelow    = { fg = colors.inconspicuous },
        CursorLineNr   = { fg = colors.yellow, bold = true },
        CursorLineSign = { fg = colors.inconspicuous, bold = true },
        CursorLineFold = { fg = colors.inconspicuous, bold = true },
        MatchParen     = { fg = colors.lime, reverse = true },
        ModeMsg        = { fg = colors.green },
        MsgArea        = { fg = colors.foreground  },
        MsgSeparator   = { fg = colors.splitline },
        MoreMsg        = { fg = colors.green },
        NonText        = { fg = colors.inconspicuous },
        Normal         = { fg = colors.foreground, bg = colors.background },
        NormalFloat    = { fg = colors.foreground, bg = colors.background },
        NormalNC       = { fg = colors.foreground, bg = colors.background },
        Pmenu          = { fg = colors.foreground, bg = colors.selection },
        PmenuSbar      = { bg = colors.inconspicuous },
        PmenuSel       = { fg = colors.selection, bg = colors.blue },
        PmenuThumb     = { bg = colors.inconspicuous },
        Question       = { fg = colors.green },
        QuickFixLine   = { bg = colors.splitline },
        Search         = { fg = colors.lime, reverse = true },
        SpecialKey     = { fg = colors.brown },
        SpellBad       = { fg = colors.red, undercurl = true },
        SpellCap       = { fg = colors.green, undercurl = true },
        SpellLocal     = { fg = colors.red, undercurl = true },
        SpellRare      = { fg = colors.blue, undercurl = true },
        StatusLine     = { fg = colors.yellow, bg = colors.stripline },
        StatusLineNC   = { fg = colors.foreground, bg = colors.stripline },
        TabLine        = { fg = colors.foreground, bg = colors.stripline },
        TabLineFill    = { bg = colors.stripline },
        TabLineSel     = { fg = colors.yellow, bg = colors.stripline },
        Title          = { fg = colors.foreground },
        Visual         = { bg = colors.selection },
        VisualNOS      = { bg = colors.red },
        WarningMsg     = { fg = colors.red },
        Whitespace     = { fg = colors.inconspicuous },
        WildMenu       = { fg = colors.green, bg = colors.stripline, bold = true },
    }
end

return M
