return function(colors)
    return {
        -- gitsigns.nvim
        GitSignsAdd = { fg = colors.green },
        GitSignsChange = { fg = colors.blue },
        GitSignsDelete = { fg = colors.red },

        -- flash.nvim
        FlashBackdrop = { fg = colors.comment, bold = false },
        FlashMatch = { fg = colors.match, bold = true },
        FlashCurrent = { fg = colors.current_match, bold = true },
        FlashLabel = { fg = colors.target, bold = true },

        -- telescope.nvim
        TelescopeBorder = { link = "FloatBorder" },
        TelescopeMatching = { fg = colors.match },

        -- noice.nvim
        NoiceMini = { link = "NormalFloat" },
        NoicePopup = { link = "NormalFloat" },
        NoicePopupBorder = { link = "FloatBorder" },
        NoiceCmdlinePopup = { link = "NormalFloat" },
        NoiceCmdlinePopupBorder = { link = "FloatBorder" },
        NoiceCmdlinePopupTitle = { link = "FloatTitle" },
        NoiceConfirm = { link = "NormalFloat" },
        NoiceConfirmBorder = { link = "FloatBorder" },
        NoiceFormatProgressDone = { fg = colors.green },
        NoiceFormatProgressTodo = { fg = colors.inconspicuous },

        -- nvim-tree.lua
        NvimTreeNormal = { link = "Normal" },
        NvimTreeNormalNC = { link = "Normal" },
        NvimTreeNormalFloat = { link = "NormalFloat" },
        NvimTreeNormalFloatBorder = { link = "FloatBorder" },
        NvimTreeWinSeparator = { link = "WinSeparator" },
        NvimTreeFolderIcon = { link = "Directory" },
        NvimTreeIndentMarker = { fg = colors.inconspicuous },
        NvimTreeRootFolder = { link = "Directory" },
        NvimTreeOpenedHL = { bg = colors.stripline },
        NvimTreeGitDeletedIcon = { link = "Removed" },
        NvimTreeGitDirtyIcon = { link = "Changed" },
        NvimTreeGitIgnoredIcon = { link = "Comment" },
        NvimTreeGitMergeIcon = { link = "Changed" },
        NvimTreeGitNewIcon = { link = "Added" },
        NvimTreeGitRenamedIcon = { link = "Changed" },
        NvimTreeGitStagedIcon = { link = "Added" },
        NvimTreeWindowPicker = { fg = colors.target, bold = true },

        -- outline.nvim
        OutlineCurrent = { fg = colors.foreground, bg = colors.stripline },
        OutlineGuides = { fg = colors.inconspicuous },
        OutlineFoldMarker = { fg = colors.comment },
        OutlineDetails = { link = "Comment" },
        OutlineLineno = { link = "LineNr" },
        OutlineJumpHighlight = { link = "Visual" },
        OutlineHelpTip = { link = "Comment" },
        OutlineStatusFt = { link = "Type" },
        OutlineStatusProvider = { link = "Special" },
        OutlineStatusError = { link = "ErrorMsg" },
        OutlineKeymapHelpKey = { link = "Special" },
        OutlineKeymapHelpDisabled = { fg = colors.inconspicuous },

        -- lazy.nvim
        LazyProgressDone = { fg = colors.green, bold = true },
        LazyProgressTodo = { fg = colors.inconspicuous },

        -- mason.nvim
        MasonNormal = { link = "NormalFloat" },
        MasonHeader = { fg = colors.blue, bold = true },
        MasonHeaderSecondary = { fg = colors.teal, bold = true },
        MasonHighlight = { fg = colors.blue },
        MasonHighlightBlock = { fg = colors.blue, bg = colors.selection },
        MasonHighlightBlockBold = { fg = colors.blue, bg = colors.selection, bold = true },
        MasonHighlightSecondary = { fg = colors.teal },
        MasonHighlightBlockSecondary = { fg = colors.teal, bg = colors.selection },
        MasonHighlightBlockBoldSecondary = { fg = colors.teal, bg = colors.selection, bold = true },
        MasonLink = { link = "MasonHighlight" },
        MasonMuted = { fg = colors.comment },
        MasonMutedBlock = { fg = colors.comment, bg = colors.stripline },
        MasonMutedBlockBold = { fg = colors.comment, bg = colors.stripline, bold = true },
        MasonError = { link = "ErrorMsg" },
        MasonWarning = { link = "WarningMsg" },
        MasonHeading = { fg = colors.foreground, bold = true },

        -- LuaSnip
        LuasnipInsertNodeActive = { bg = colors.selection },
        LuasnipChoiceNodeActive = { fg = colors.target, bold = true },
        LuasnipDynamicNodeActive = { bg = colors.stripline },
        LuasnipSnippetNodeActive = { bg = colors.stripline },
        LuasnipRestoreNodeActive = { bg = colors.stripline },
        LuasnipExitNodeActive = { fg = colors.inconspicuous },

        -- trouble.nvim
        TroubleNormal = { link = "Normal" },
        TroubleText = { fg = colors.foreground },
        TroubleCount = { fg = colors.comment },

        -- todo-comments.nvim
        TodoFgFIX = { fg = colors.red },
        TodoBgFIX = { fg = colors.background, bg = colors.red, bold = true },
        TodoSignFIX = { fg = colors.red },
        TodoFgTODO = { fg = colors.blue },
        TodoBgTODO = { fg = colors.background, bg = colors.blue, bold = true },
        TodoSignTODO = { fg = colors.blue },
        TodoFgHACK = { fg = colors.yellow },
        TodoBgHACK = { fg = colors.background, bg = colors.yellow, bold = true },
        TodoSignHACK = { fg = colors.yellow },
        TodoFgWARN = { fg = colors.yellow },
        TodoBgWARN = { fg = colors.background, bg = colors.yellow, bold = true },
        TodoSignWARN = { fg = colors.yellow },
        TodoFgPERF = { fg = colors.purple },
        TodoBgPERF = { fg = colors.background, bg = colors.purple, bold = true },
        TodoSignPERF = { fg = colors.purple },
        TodoFgNOTE = { fg = colors.teal },
        TodoBgNOTE = { fg = colors.background, bg = colors.teal, bold = true },
        TodoSignNOTE = { fg = colors.teal },
        TodoFgTEST = { fg = colors.violet },
        TodoBgTEST = { fg = colors.background, bg = colors.violet, bold = true },
        TodoSignTEST = { fg = colors.violet },

        -- indent-blankline.nvim
        IblIndent = { fg = colors.inconspicuous, nocombine = true },
        IblWhitespace = { fg = colors.inconspicuous, nocombine = true },
        IblScope = { fg = colors.splitline, nocombine = true },

        -- nvim-dap
        DapStoppedLine = { bg = colors.stripline },

        -- nvim-dap-ui
        DapUINormal = { link = "Normal" },
        DapUIVariable = { link = "Identifier" },
        DapUIScope = { link = "Type" },
        DapUIType = { link = "Type" },
        DapUIValue = { link = "Constant" },
        DapUIModifiedValue = { link = "Function" },
        DapUIDecoration = { fg = colors.comment },
        DapUIThread = { link = "Identifier" },
        DapUIStoppedThread = { fg = colors.current_match, bold = true },
        DapUIFrameName = { fg = colors.foreground },
        DapUISource = { link = "Directory" },
        DapUILineNumber = { link = "LineNr" },
        DapUIFloatNormal = { link = "NormalFloat" },
        DapUIFloatBorder = { link = "FloatBorder" },
        DapUIWatchesEmpty = { link = "Comment" },
        DapUIWatchesValue = { link = "Constant" },
        DapUIWatchesError = { link = "DiagnosticError" },
        DapUIBreakpointsPath = { link = "Directory" },
        DapUIBreakpointsInfo = { link = "DiagnosticInfo" },
        DapUIBreakpointsCurrentLine = { link = "CursorLineNr" },
        DapUIBreakpointsDisabledLine = { fg = colors.inconspicuous },
        DapUIUnavailable = { fg = colors.inconspicuous },
        DapUIWinSelect = { fg = colors.target, bold = true },

        -- snacks.nvim
        SnacksNotifierDebug = { link = "NormalFloat" },
        SnacksNotifierBorderDebug = { link = "FloatBorder" },
        SnacksNotifierIconDebug = { link = "Comment" },
        SnacksNotifierTitleDebug = { link = "Comment" },
        SnacksNotifierError = { link = "NormalFloat" },
        SnacksNotifierBorderError = { link = "DiagnosticError" },
        SnacksNotifierIconError = { link = "DiagnosticError" },
        SnacksNotifierTitleError = { link = "DiagnosticError" },
        SnacksNotifierInfo = { link = "NormalFloat" },
        SnacksNotifierBorderInfo = { link = "DiagnosticInfo" },
        SnacksNotifierIconInfo = { link = "DiagnosticInfo" },
        SnacksNotifierTitleInfo = { link = "DiagnosticInfo" },
        SnacksNotifierTrace = { link = "NormalFloat" },
        SnacksNotifierBorderTrace = { fg = colors.violet },
        SnacksNotifierIconTrace = { fg = colors.violet },
        SnacksNotifierTitleTrace = { fg = colors.violet },
        SnacksNotifierWarn = { link = "NormalFloat" },
        SnacksNotifierBorderWarn = { link = "DiagnosticWarn" },
        SnacksNotifierIconWarn = { link = "DiagnosticWarn" },
        SnacksNotifierTitleWarn = { link = "DiagnosticWarn" },
        SnacksDashboardDesc = { fg = colors.foreground },
        SnacksDashboardFooter = { fg = colors.comment },
        SnacksDashboardHeader = { fg = colors.blue },
        SnacksDashboardIcon = { fg = colors.comment },
        SnacksDashboardKey = { fg = colors.target, bold = true },
        SnacksDashboardSpecial = { fg = colors.purple },
        SnacksDashboardDir = { fg = colors.inconspicuous },
        SnacksIndent = { fg = colors.inconspicuous, nocombine = true },
        SnacksIndentScope = { fg = colors.splitline, nocombine = true },
        SnacksInputBorder = { link = "FloatBorder" },
        SnacksInputTitle = { link = "FloatTitle" },
        SnacksPickerInputBorder = { link = "FloatBorder" },
        SnacksPickerInputTitle = { link = "FloatTitle" },
        SnacksPickerBoxTitle = { link = "FloatTitle" },
        SnacksPickerMatch = { fg = colors.match },
        SnacksPickerSelected = { bg = colors.selection },
        SnacksPickerDirectory = { link = "Directory" },
        SnacksPickerDir = { fg = colors.comment },
        SnacksPickerFile = { fg = colors.foreground },

        -- blink.cmp
        BlinkCmpDoc = { link = "NormalFloat" },
        BlinkCmpDocBorder = { link = "FloatBorder" },
        BlinkCmpGhostText = { fg = colors.inconspicuous },
        BlinkCmpLabel = { fg = colors.foreground },
        BlinkCmpLabelDeprecated = { fg = colors.inconspicuous, strikethrough = true },
        BlinkCmpLabelMatch = { fg = colors.match },
        BlinkCmpMenu = { link = "NormalFloat" },
        BlinkCmpMenuBorder = { link = "FloatBorder" },
        BlinkCmpSignatureHelp = { link = "NormalFloat" },
        BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
        BlinkCmpKindDefault = { fg = colors.comment },
        BlinkCmpKindText = { link = "Identifier" },
        BlinkCmpKindMethod = { link = "@lsp.type.method" },
        BlinkCmpKindFunction = { link = "@lsp.type.function" },
        BlinkCmpKindConstructor = { link = "@lsp.type.function" },
        BlinkCmpKindField = { link = "@lsp.type.property" },
        BlinkCmpKindVariable = { link = "@lsp.type.variable" },
        BlinkCmpKindClass = { link = "@lsp.type.class" },
        BlinkCmpKindInterface = { link = "@lsp.type.interface" },
        BlinkCmpKindModule = { link = "@lsp.type.namespace" },
        BlinkCmpKindProperty = { link = "@lsp.type.property" },
        BlinkCmpKindUnit = { link = "Constant" },
        BlinkCmpKindValue = { link = "Constant" },
        BlinkCmpKindEnum = { link = "@lsp.type.enum" },
        BlinkCmpKindKeyword = { link = "Keyword" },
        BlinkCmpKindSnippet = { link = "@lsp.type.macro" },
        BlinkCmpKindColor = { link = "Constant" },
        BlinkCmpKindFile = { link = "Directory" },
        BlinkCmpKindReference = { link = "Identifier" },
        BlinkCmpKindFolder = { link = "Directory" },
        BlinkCmpKindEnumMember = { link = "@lsp.type.enumMember" },
        BlinkCmpKindConstant = { link = "Constant" },
        BlinkCmpKindStruct = { link = "@lsp.type.struct" },
        BlinkCmpKindEvent = { link = "@lsp.type.event" },
        BlinkCmpKindOperator = { link = "Operator" },
        BlinkCmpKindTypeParameter = { link = "@lsp.type.typeParameter" },
        BlinkCmpKindCopilot = { fg = colors.teal },
        BlinkCmpKindCodeium = { fg = colors.teal },
        BlinkCmpKindSupermaven = { fg = colors.teal },
        BlinkCmpKindTabNine = { fg = colors.teal },

        -- nvim-cmp
        CmpItemAbbr = { fg = colors.foreground },
        CmpItemAbbrDeprecated = { link = "Ignore" },
        CmpItemAbbrMatch = { fg = colors.match },
        CmpItemAbbrMatchFuzzy = { fg = colors.match },
        CmpItemKind = { fg = colors.comment },
        CmpItemKindIcon = { link = "CmpItemKind" },
        CmpItemMenu = { fg = colors.comment },

        CmpItemKindDefault = { link = "CmpItemKind" },
        CmpItemKindText = { link = "Identifier" },
        CmpItemKindMethod = { link = "@lsp.type.method" },
        CmpItemKindFunction = { link = "@lsp.type.function" },
        CmpItemKindConstructor = { link = "@lsp.type.function" },
        CmpItemKindField = { link = "@lsp.type.property" },
        CmpItemKindVariable = { link = "@lsp.type.variable" },
        CmpItemKindClass = { link = "@lsp.type.class" },
        CmpItemKindInterface = { link = "@lsp.type.interface" },
        CmpItemKindModule = { link = "@lsp.type.namespace" },
        CmpItemKindProperty = { link = "@lsp.type.property" },
        CmpItemKindUnit = { link = "Constant" },
        CmpItemKindValue = { link = "Constant" },
        CmpItemKindEnum = { link = "@lsp.type.enum" },
        CmpItemKindKeyword = { link = "Keyword" },
        CmpItemKindSnippet = { link = "@lsp.type.macro" },
        CmpItemKindColor = { link = "Constant" },
        CmpItemKindFile = { link = "Directory" },
        CmpItemKindReference = { link = "Identifier" },
        CmpItemKindFolder = { link = "Directory" },
        CmpItemKindEnumMember = { link = "@lsp.type.enumMember" },
        CmpItemKindConstant = { link = "Constant" },
        CmpItemKindStruct = { link = "@lsp.type.struct" },
        CmpItemKindEvent = { link = "@lsp.type.event" },
        CmpItemKindOperator = { link = "Operator" },
        CmpItemKindTypeParameter = { link = "@lsp.type.typeParameter" },

        -- Compatibility with completion sources that expose non-standard kinds.
        CmpItemKindDecorator = { link = "@lsp.type.decorator" },
        CmpItemKindMacro = { link = "@lsp.type.macro" },
        CmpItemKindNamespace = { link = "@lsp.type.namespace" },
        CmpItemKindType = { link = "@lsp.type.type" },

        CmpItemKindTextIcon = { link = "CmpItemKindText" },
        CmpItemKindMethodIcon = { link = "CmpItemKindMethod" },
        CmpItemKindFunctionIcon = { link = "CmpItemKindFunction" },
        CmpItemKindConstructorIcon = { link = "CmpItemKindConstructor" },
        CmpItemKindFieldIcon = { link = "CmpItemKindField" },
        CmpItemKindVariableIcon = { link = "CmpItemKindVariable" },
        CmpItemKindClassIcon = { link = "CmpItemKindClass" },
        CmpItemKindInterfaceIcon = { link = "CmpItemKindInterface" },
        CmpItemKindModuleIcon = { link = "CmpItemKindModule" },
        CmpItemKindPropertyIcon = { link = "CmpItemKindProperty" },
        CmpItemKindUnitIcon = { link = "CmpItemKindUnit" },
        CmpItemKindValueIcon = { link = "CmpItemKindValue" },
        CmpItemKindEnumIcon = { link = "CmpItemKindEnum" },
        CmpItemKindKeywordIcon = { link = "CmpItemKindKeyword" },
        CmpItemKindSnippetIcon = { link = "CmpItemKindSnippet" },
        CmpItemKindColorIcon = { link = "CmpItemKindColor" },
        CmpItemKindFileIcon = { link = "CmpItemKindFile" },
        CmpItemKindReferenceIcon = { link = "CmpItemKindReference" },
        CmpItemKindFolderIcon = { link = "CmpItemKindFolder" },
        CmpItemKindEnumMemberIcon = { link = "CmpItemKindEnumMember" },
        CmpItemKindConstantIcon = { link = "CmpItemKindConstant" },
        CmpItemKindStructIcon = { link = "CmpItemKindStruct" },
        CmpItemKindEventIcon = { link = "CmpItemKindEvent" },
        CmpItemKindOperatorIcon = { link = "CmpItemKindOperator" },
        CmpItemKindTypeParameterIcon = { link = "CmpItemKindTypeParameter" },

        -- which-key.nvim
        WhichKey = { link = "Function" },
        WhichKeySeparator = { link = "Comment" },
        WhichKeyDesc = { link = "Identifier" },
        WhichKeyGroup = { link = "Keyword" },
        WhichKeyValue = { link = "Comment" },

        -- rainbow-delimiters.nvim
        -- The plugin currently exposes seven default slots. Nova intentionally
        -- omits orange in the seven-color cycle and uses purple in that slot.
        RainbowDelimiterRed = { fg = colors.red },
        RainbowDelimiterYellow = { fg = colors.yellow },
        RainbowDelimiterBlue = { fg = colors.blue },
        RainbowDelimiterOrange = { fg = colors.purple },
        RainbowDelimiterGreen = { fg = colors.green },
        RainbowDelimiterViolet = { fg = colors.violet },
        RainbowDelimiterCyan = { fg = colors.teal },
    }
end
