return function(colors)
    return {
        -- Modern Tree-sitter captures. Prefer links so existing Nova color semantics stay unchanged.
        ["@variable"] = { link = "Identifier" },
        ["@variable.builtin"] = { link = "Identifier" },
        ["@variable.parameter"] = { link = "@lsp.type.parameter" },
        ["@variable.parameter.builtin"] = { link = "@lsp.type.parameter" },
        ["@variable.member"] = { link = "@lsp.type.property" },

        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Constant" },
        ["@constant.macro"] = { link = "Macro" },
        ["@module"] = { link = "@lsp.type.namespace" },
        ["@module.builtin"] = { link = "@lsp.type.namespace" },
        ["@label"] = { link = "Label" },

        ["@string"] = { link = "String" },
        ["@string.documentation"] = { link = "String" },
        ["@string.regexp"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "Special" },
        ["@string.special.symbol"] = { link = "Special" },
        ["@string.special.path"] = { link = "String" },
        ["@string.special.url"] = { link = "Underlined" },

        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },

        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "Type" },
        ["@type.definition"] = { link = "Typedef" },
        ["@attribute"] = { link = "PreProc" },
        ["@attribute.builtin"] = { link = "PreProc" },
        ["@property"] = { link = "@lsp.type.property" },

        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Function" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@function.method"] = { link = "Function" },
        ["@function.method.call"] = { link = "Function" },
        ["@constructor"] = { link = "Type" },
        ["@operator"] = { link = "Operator" },

        ["@keyword"] = { link = "Keyword" },
        ["@keyword.coroutine"] = { link = "Keyword" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.operator"] = { link = "Keyword" },
        ["@keyword.import"] = { link = "Include" },
        ["@keyword.type"] = { link = "Keyword" },
        ["@keyword.modifier"] = { link = "StorageClass" },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@keyword.debug"] = { link = "Debug" },
        ["@keyword.exception"] = { link = "Exception" },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.conditional.ternary"] = { link = "Conditional" },
        ["@keyword.directive"] = { link = "PreProc" },
        ["@keyword.directive.define"] = { link = "Define" },

        ["@punctuation.delimiter"] = { link = "Delimiter" },
        ["@punctuation.bracket"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Special" },

        ["@comment"] = { link = "Comment" },
        ["@comment.documentation"] = { link = "Comment" },
        ["@comment.error"] = { fg = colors.red, bold = true },
        ["@comment.warning"] = { fg = colors.yellow, bold = true },
        ["@comment.todo"] = { fg = colors.violet, bold = true },
        ["@comment.note"] = { fg = colors.green, bold = true },

        ["@markup.heading"] = { fg = colors.blue, bold = true },
        ["@markup.heading.1"] = { link = "@markup.heading" },
        ["@markup.heading.2"] = { link = "@markup.heading" },
        ["@markup.heading.3"] = { link = "@markup.heading" },
        ["@markup.heading.4"] = { link = "@markup.heading" },
        ["@markup.heading.5"] = { link = "@markup.heading" },
        ["@markup.heading.6"] = { link = "@markup.heading" },
        ["@markup.raw"] = { fg = colors.violet },
        ["@markup.raw.block"] = { link = "@markup.raw" },
        ["@markup.link"] = { fg = colors.green, bold = true },
        ["@markup.link.label"] = { link = "@markup.link" },
        ["@markup.link.url"] = { fg = colors.teal, underline = true },
        ["@markup.italic"] = { fg = colors.violet, italic = true },
        ["@markup.strong"] = { fg = colors.violet, bold = true },
        ["@markup.strikethrough"] = { fg = colors.violet, strikethrough = true },

        ["@diff.plus"] = { link = "DiffAdd" },
        ["@diff.minus"] = { link = "DiffDelete" },
        ["@diff.delta"] = { link = "DiffChange" },

        -- Compatibility with older queries/parsers.
        ["@parameter"] = { link = "@variable.parameter" },
        ["@field"] = { link = "@variable.member" },
        ["@namespace"] = { link = "@module" },
        ["@text.todo"] = { link = "@comment.todo" },
        ["@text.note"] = { link = "@comment.note" },
        ["@text.warning"] = { link = "@comment.warning" },
        ["@text.danger"] = { link = "@comment.error" },
        ["@text.title"] = { link = "@markup.heading" },
        ["@text.literal"] = { link = "@markup.raw" },
        ["@text.reference"] = { link = "@markup.link" },
        ["@text.uri"] = { link = "@markup.link.url" },
        ["@text.emphasis"] = { link = "@markup.italic" },
        ["@text.strike"] = { link = "@markup.strikethrough" },
        ["@text.strong"] = { link = "@markup.strong" },
    }
end
