local M = {}

local variants = { "default", "dim", "soft" }
local appearances = { "dark", "light" }

local function join(lines)
    return table.concat(lines, "\n") .. "\n"
end

local function header(prefix)
    return string.format("%s Generated by scripts/generate_themes.lua; do not edit.\n", prefix)
end

local function slug(appearance, variant)
    return "nova-" .. appearance .. (variant == "default" and "" or "-" .. variant)
end

local function display_name(appearance, variant)
    local words = { "Nova", appearance:sub(1, 1):upper() .. appearance:sub(2) }
    if variant ~= "default" then
        words[#words + 1] = variant:sub(1, 1):upper() .. variant:sub(2)
    end
    return table.concat(words, " ")
end

local function json_encode(value, level)
    level = level or 0
    local indent = string.rep("  ", level)
    local child_indent = string.rep("  ", level + 1)

    if type(value) ~= "table" then
        return vim.json.encode(value)
    end

    if vim.islist(value) then
        if #value == 0 then
            return "[]"
        end
        local encoded = {}
        for _, item in ipairs(value) do
            encoded[#encoded + 1] = child_indent .. json_encode(item, level + 1)
        end
        return "[\n" .. table.concat(encoded, ",\n") .. "\n" .. indent .. "]"
    end

    local keys = vim.tbl_keys(value)
    table.sort(keys)
    if #keys == 0 then
        return "{}"
    end

    local encoded = {}
    for _, key in ipairs(keys) do
        encoded[#encoded + 1] = string.format(
            "%s%s: %s",
            child_indent,
            vim.json.encode(key),
            json_encode(value[key], level + 1)
        )
    end
    return "{\n" .. table.concat(encoded, ",\n") .. "\n" .. indent .. "}"
end

local function derive(appearance, variant)
    local colors = require("nova.colors").setup({ colors = {}, variant = variant }, appearance)
    local blend = require("nova.utils").blend
    local anchor = appearance == "dark" and "#ffffff" or "#000000"
    local function intense(color)
        return blend(color, anchor, 0.88)
    end

    return {
        appearance = appearance,
        variant = variant,
        slug = slug(appearance, variant),
        name = display_name(appearance, variant),
        colors = colors,
        ansi = {
            colors.background,
            colors.red,
            colors.green,
            colors.yellow,
            colors.blue,
            colors.purple,
            colors.teal,
            colors.foreground,
        },
        brights = {
            colors.comment,
            intense(colors.red),
            intense(colors.green),
            intense(colors.yellow),
            intense(colors.blue),
            intense(colors.purple),
            intense(colors.teal),
            intense(colors.foreground),
        },
    }
end

local function windows_terminal(theme)
    local c = theme.colors
    local a = theme.ansi
    local b = theme.brights
    return {
        name = theme.name,
        background = c.background,
        foreground = c.foreground,
        cursorColor = c.red,
        selectionBackground = c.selection,
        black = a[1],
        red = a[2],
        green = a[3],
        yellow = a[4],
        blue = a[5],
        purple = a[6],
        cyan = a[7],
        white = a[8],
        brightBlack = b[1],
        brightRed = b[2],
        brightGreen = b[3],
        brightYellow = b[4],
        brightBlue = b[5],
        brightPurple = b[6],
        brightCyan = b[7],
        brightWhite = b[8],
    }
end

local function toml_array(values)
    local quoted = {}
    for _, value in ipairs(values) do
        quoted[#quoted + 1] = string.format("%q", value)
    end
    return "[" .. table.concat(quoted, ", ") .. "]"
end

local function wezterm(theme)
    local c = theme.colors
    return header("#") .. join({
        "[colors]",
        string.format("foreground = %q", c.foreground),
        string.format("background = %q", c.background),
        string.format("cursor_bg = %q", c.red),
        string.format("cursor_border = %q", c.red),
        string.format("cursor_fg = %q", c.background),
        string.format("selection_bg = %q", c.selection),
        string.format("selection_fg = %q", c.foreground),
        string.format("scrollbar_thumb = %q", c.comment),
        string.format("split = %q", c.splitline),
        "ansi = " .. toml_array(theme.ansi),
        "brights = " .. toml_array(theme.brights),
        "",
        "[metadata]",
        string.format("name = %q", theme.name),
        'origin_url = "https://github.com/zanglg/nova.nvim"',
    })
end

local ansi_names = { "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white" }

local function alacritty(theme)
    local c = theme.colors
    local lines = {
        header("#"):gsub("\n$", ""),
        "[colors.primary]",
        string.format("background = %q", c.background),
        string.format("foreground = %q", c.foreground),
        string.format("dim_foreground = %q", c.comment),
        "",
        "[colors.cursor]",
        string.format("cursor = %q", c.red),
        string.format("text = %q", c.background),
        "",
        "[colors.vi_mode_cursor]",
        string.format("cursor = %q", c.target),
        string.format("text = %q", c.background),
        "",
        "[colors.search.matches]",
        string.format("foreground = %q", c.background),
        string.format("background = %q", c.match),
        "",
        "[colors.search.focused_match]",
        string.format("foreground = %q", c.background),
        string.format("background = %q", c.current_match),
        "",
        "[colors.hints.start]",
        string.format("foreground = %q", c.background),
        string.format("background = %q", c.target),
        "",
        "[colors.hints.end]",
        string.format("foreground = %q", c.target),
        string.format("background = %q", c.background),
        "",
        "[colors.selection]",
        string.format("text = %q", c.foreground),
        string.format("background = %q", c.selection),
        "",
        "[colors.footer_bar]",
        string.format("foreground = %q", c.foreground),
        string.format("background = %q", c.popupmenu),
        "",
        "[colors.normal]",
    }
    for index, name in ipairs(ansi_names) do
        lines[#lines + 1] = string.format("%s = %q", name, theme.ansi[index])
    end
    lines[#lines + 1] = ""
    lines[#lines + 1] = "[colors.bright]"
    for index, name in ipairs(ansi_names) do
        lines[#lines + 1] = string.format("%s = %q", name, theme.brights[index])
    end
    return join(lines)
end

local function kitty(theme)
    local c = theme.colors
    local lines = {
        header("#"):gsub("\n$", ""),
        "foreground " .. c.foreground,
        "background " .. c.background,
        "selection_foreground " .. c.foreground,
        "selection_background " .. c.selection,
        "cursor " .. c.red,
        "cursor_text_color " .. c.background,
        "url_color " .. c.teal,
        "active_border_color " .. c.target,
        "inactive_border_color " .. c.splitline,
        "bell_border_color " .. c.yellow,
        "active_tab_foreground " .. c.background,
        "active_tab_background " .. c.blue,
        "inactive_tab_foreground " .. c.comment,
        "inactive_tab_background " .. c.popupmenu,
        "tab_bar_background " .. c.stripline,
        "mark1_foreground " .. c.background,
        "mark1_background " .. c.red,
        "mark2_foreground " .. c.background,
        "mark2_background " .. c.green,
        "mark3_foreground " .. c.background,
        "mark3_background " .. c.blue,
        "",
    }
    for index, color in ipairs(theme.ansi) do
        lines[#lines + 1] = string.format("color%d %s", index - 1, color)
    end
    for index, color in ipairs(theme.brights) do
        lines[#lines + 1] = string.format("color%d %s", index + 7, color)
    end
    return join(lines)
end

local function ghostty(theme)
    local c = theme.colors
    local lines = { header("#"):gsub("\n$", "") }
    for index, color in ipairs(theme.ansi) do
        lines[#lines + 1] = string.format("palette = %d=%s", index - 1, color)
    end
    for index, color in ipairs(theme.brights) do
        lines[#lines + 1] = string.format("palette = %d=%s", index + 7, color)
    end
    vim.list_extend(lines, {
        "background = " .. c.background,
        "foreground = " .. c.foreground,
        "cursor-color = " .. c.red,
        "cursor-text = " .. c.background,
        "selection-background = " .. c.selection,
        "selection-foreground = " .. c.foreground,
    })
    return join(lines)
end

local function fzf(theme)
    local c = theme.colors
    local values = {
        "fg:" .. c.foreground,
        "fg+:" .. c.foreground,
        "bg:" .. c.background,
        "bg+:" .. c.selection,
        "hl:" .. c.match,
        "hl+:" .. c.current_match,
        "info:" .. c.comment,
        "marker:" .. c.green,
        "prompt:" .. c.blue,
        "spinner:" .. c.teal,
        "pointer:" .. c.target,
        "header:" .. c.violet,
        "border:" .. c.splitline,
        "label:" .. c.comment,
        "query:" .. c.foreground,
        "gutter:" .. c.background,
        "preview-border:" .. c.splitline,
        "list-border:" .. c.splitline,
        "input-border:" .. c.splitline,
        "header-border:" .. c.splitline,
    }
    return header("#")
        .. string.format("export FZF_DEFAULT_OPTS=\"${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=%s\"\n", table.concat(values, ","))
end

local function helix(theme)
    local c = theme.colors
    local lines = {
        header("#"):gsub("\n$", ""),
        '"attribute" = "orange"',
        '"type" = "red"',
        '"type.builtin" = "red"',
        '"constructor" = "red"',
        '"constant" = "yellow"',
        '"constant.builtin" = "yellow"',
        '"constant.numeric" = "yellow"',
        '"constant.character.escape" = "orange"',
        '"string" = "green"',
        '"string.regexp" = "teal"',
        '"string.special" = "violet"',
        '"comment" = { fg = "comment", modifiers = ["italic"] }',
        '"variable" = "foreground"',
        '"variable.builtin" = "teal"',
        '"variable.parameter" = "foreground"',
        '"variable.other.member" = "violet"',
        '"label" = "orange"',
        '"punctuation" = "foreground"',
        '"punctuation.special" = "orange"',
        '"keyword" = "purple"',
        '"keyword.directive" = "violet"',
        '"keyword.storage.modifier" = "teal"',
        '"keyword.control.return" = "purple"',
        '"keyword.control.exception" = "purple"',
        '"operator" = "foreground"',
        '"function" = "blue"',
        '"function.builtin" = "blue"',
        '"function.macro" = "orange"',
        '"tag" = "orange"',
        '"namespace" = "violet"',
        '"special" = "orange"',
        '"markup.heading" = { fg = "blue", modifiers = ["bold"] }',
        '"markup.list" = "purple"',
        '"markup.bold" = { modifiers = ["bold"] }',
        '"markup.italic" = { modifiers = ["italic"] }',
        '"markup.strikethrough" = { modifiers = ["crossed_out"] }',
        '"markup.link.text" = "green"',
        '"markup.link.url" = { fg = "teal", underline = { style = "line" } }',
        '"markup.quote" = { fg = "comment", modifiers = ["italic"] }',
        '"markup.raw" = "violet"',
        '"diff.plus" = "green"',
        '"diff.delta" = "blue"',
        '"diff.minus" = "red"',
        '"ui.background" = { fg = "foreground", bg = "background" }',
        '"ui.background.separator" = "splitline"',
        '"ui.window" = "splitline"',
        '"ui.text" = "foreground"',
        '"ui.text.focus" = { fg = "foreground", bg = "selection" }',
        '"ui.text.inactive" = "inconspicuous"',
        '"ui.text.directory" = "blue"',
        '"ui.virtual" = "inconspicuous"',
        '"ui.virtual.ruler" = { bg = "stripline" }',
        '"ui.virtual.inlay-hint" = { fg = "inconspicuous", modifiers = ["italic"] }',
        '"ui.virtual.jump-label" = { fg = "target", modifiers = ["bold"] }',
        '"ui.linenr" = "comment"',
        '"ui.linenr.selected" = { fg = "blue", modifiers = ["bold"] }',
        '"ui.statusline" = { fg = "foreground", bg = "selection" }',
        '"ui.statusline.inactive" = { fg = "comment", bg = "stripline" }',
        '"ui.statusline.normal" = { fg = "background", bg = "blue", modifiers = ["bold"] }',
        '"ui.statusline.insert" = { fg = "background", bg = "green", modifiers = ["bold"] }',
        '"ui.statusline.select" = { fg = "background", bg = "purple", modifiers = ["bold"] }',
        '"ui.bufferline" = { fg = "comment", bg = "popupmenu" }',
        '"ui.bufferline.active" = { fg = "foreground", bg = "selection" }',
        '"ui.popup" = { fg = "foreground", bg = "popupmenu" }',
        '"ui.help" = { fg = "foreground", bg = "popupmenu" }',
        '"ui.menu" = { fg = "foreground", bg = "popupmenu" }',
        '"ui.menu.selected" = { fg = "foreground", bg = "selection" }',
        '"ui.menu.scroll" = { fg = "comment", bg = "stripline" }',
        '"ui.selection" = { bg = "selection" }',
        '"ui.selection.primary" = { bg = "selection" }',
        '"ui.cursor" = { fg = "background", bg = "red" }',
        '"ui.cursor.primary" = { fg = "background", bg = "red" }',
        '"ui.cursor.insert" = { fg = "background", bg = "green" }',
        '"ui.cursor.select" = { fg = "background", bg = "purple" }',
        '"ui.cursor.match" = { fg = "background", bg = "current_match" }',
        '"ui.cursorline.primary" = { bg = "stripline" }',
        '"ui.highlight" = { bg = "selection" }',
        '"ui.highlight.frameline" = { bg = "popupmenu" }',
        '"ui.debug.breakpoint" = "red"',
        '"ui.debug.active" = "yellow"',
        '"ui.picker.header.column.active" = { fg = "blue", underline = { style = "line" } }',
        '"error" = "red"',
        '"warning" = "yellow"',
        '"info" = "blue"',
        '"hint" = "teal"',
        '"diagnostic.error" = { underline = { color = "red", style = "curl" } }',
        '"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }',
        '"diagnostic.info" = { underline = { color = "blue", style = "curl" } }',
        '"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }',
        '"diagnostic.unnecessary" = { modifiers = ["dim"] }',
        '"diagnostic.deprecated" = { modifiers = ["crossed_out"] }',
        'rainbow = ["red", "orange", "yellow", "green", "teal", "blue", "violet", "purple"]',
        "",
        "[palette]",
    }
    local palette_order = {
        "foreground",
        "comment",
        "inconspicuous",
        "splitline",
        "selection",
        "popupmenu",
        "stripline",
        "background",
        "red",
        "orange",
        "yellow",
        "green",
        "teal",
        "blue",
        "violet",
        "purple",
        "match",
        "current_match",
        "target",
    }
    for _, name in ipairs(palette_order) do
        lines[#lines + 1] = string.format("%s = %q", name, c[name])
    end
    return join(lines)
end

local function pi_theme(theme)
    local c = theme.colors
    local data = {
        ["$schema"] = "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
        name = theme.slug,
        vars = {
            foreground = c.foreground,
            comment = c.comment,
            inconspicuous = c.inconspicuous,
            splitline = c.splitline,
            selection = c.selection,
            popupmenu = c.popupmenu,
            stripline = c.stripline,
            background = c.background,
            red = c.red,
            orange = c.orange,
            yellow = c.yellow,
            green = c.green,
            teal = c.teal,
            blue = c.blue,
            violet = c.violet,
            purple = c.purple,
            match = c.match,
            currentMatch = c.current_match,
            target = c.target,
            diffAddBg = c.diff_add_bg,
            diffChangeBg = c.diff_change_bg,
            diffDeleteBg = c.diff_delete_bg,
        },
        colors = {
            accent = "target",
            border = "splitline",
            borderAccent = "blue",
            borderMuted = "inconspicuous",
            success = "green",
            error = "red",
            warning = "yellow",
            muted = "comment",
            dim = "inconspicuous",
            text = "foreground",
            thinkingText = "comment",
            selectedBg = "selection",
            scrollbarTrack = "splitline",
            scrollbarThumb = "comment",
            searchMatchBg = "match",
            searchMatchText = "background",
            userMessageBg = "stripline",
            userMessageText = "foreground",
            customMessageBg = "popupmenu",
            customMessageText = "foreground",
            customMessageLabel = "violet",
            toolPendingBg = "popupmenu",
            toolSuccessBg = "diffAddBg",
            toolErrorBg = "diffDeleteBg",
            toolTitle = "blue",
            toolOutput = "comment",
            mdHeading = "blue",
            mdLink = "green",
            mdLinkUrl = "teal",
            mdCode = "violet",
            mdCodeBlock = "foreground",
            mdCodeBlockBorder = "splitline",
            mdQuote = "comment",
            mdQuoteBorder = "splitline",
            mdHr = "splitline",
            mdListBullet = "purple",
            toolDiffAdded = "green",
            toolDiffRemoved = "red",
            toolDiffContext = "comment",
            syntaxComment = "comment",
            syntaxKeyword = "purple",
            syntaxFunction = "blue",
            syntaxVariable = "foreground",
            syntaxString = "green",
            syntaxNumber = "yellow",
            syntaxType = "red",
            syntaxOperator = "foreground",
            syntaxPunctuation = "foreground",
            thinkingOff = "inconspicuous",
            thinkingMinimal = "comment",
            thinkingLow = "blue",
            thinkingMedium = "teal",
            thinkingHigh = "violet",
            thinkingXhigh = "purple",
            thinkingMax = "red",
            bashMode = "green",
        },
        export = {
            pageBg = c.background,
            cardBg = c.stripline,
            infoBg = c.popupmenu,
        },
    }
    return json_encode(data) .. "\n"
end

local function yaml_style(color, attributes)
    local fields = { string.format('foreground: "%s"', color) }
    for _, attribute in ipairs(attributes or {}) do
        fields[#fields + 1] = attribute .. ": true"
    end
    return "{" .. table.concat(fields, ", ") .. "}"
end

local function eza(theme)
    local c = theme.colors
    local lines = {
        header("#"):gsub("\n$", ""),
        "colourful: true",
        "",
        "filekinds:",
        "  normal: " .. yaml_style(c.foreground),
        "  directory: " .. yaml_style(c.blue, { "is_bold" }),
        "  symlink: " .. yaml_style(c.teal),
        "  pipe: " .. yaml_style(c.comment),
        "  block_device: " .. yaml_style(c.red),
        "  char_device: " .. yaml_style(c.red),
        "  socket: " .. yaml_style(c.inconspicuous),
        "  special: " .. yaml_style(c.purple),
        "  executable: " .. yaml_style(c.green),
        "  mount_point: " .. yaml_style(c.orange),
        "perms:",
        "  user_read: " .. yaml_style(c.foreground),
        "  user_write: " .. yaml_style(c.yellow),
        "  user_execute_file: " .. yaml_style(c.green),
        "  user_execute_other: " .. yaml_style(c.green),
        "  group_read: " .. yaml_style(c.comment),
        "  group_write: " .. yaml_style(c.yellow),
        "  group_execute: " .. yaml_style(c.green),
        "  other_read: " .. yaml_style(c.comment),
        "  other_write: " .. yaml_style(c.yellow),
        "  other_execute: " .. yaml_style(c.green),
        "  special_user_file: " .. yaml_style(c.purple),
        "  special_other: " .. yaml_style(c.inconspicuous),
        "  attribute: " .. yaml_style(c.comment),
        "size:",
        "  major: " .. yaml_style(c.comment),
        "  minor: " .. yaml_style(c.teal),
        "  number_byte: " .. yaml_style(c.foreground),
        "  number_kilo: " .. yaml_style(c.foreground),
        "  number_mega: " .. yaml_style(c.blue),
        "  number_giga: " .. yaml_style(c.violet),
        "  number_huge: " .. yaml_style(c.purple),
        "  unit_byte: " .. yaml_style(c.comment),
        "  unit_kilo: " .. yaml_style(c.comment),
        "  unit_mega: " .. yaml_style(c.blue),
        "  unit_giga: " .. yaml_style(c.violet),
        "  unit_huge: " .. yaml_style(c.purple),
        "users:",
        "  user_you: " .. yaml_style(c.foreground),
        "  user_root: " .. yaml_style(c.red),
        "  user_other: " .. yaml_style(c.violet),
        "  group_yours: " .. yaml_style(c.comment),
        "  group_other: " .. yaml_style(c.inconspicuous),
        "  group_root: " .. yaml_style(c.red),
        "links:",
        "  normal: " .. yaml_style(c.teal),
        "  multi_link_file: " .. yaml_style(c.blue),
        "git:",
        "  new: " .. yaml_style(c.green),
        "  modified: " .. yaml_style(c.yellow),
        "  deleted: " .. yaml_style(c.red),
        "  renamed: " .. yaml_style(c.teal),
        "  typechange: " .. yaml_style(c.violet),
        "  ignored: " .. yaml_style(c.inconspicuous),
        "  conflicted: " .. yaml_style(c.orange),
        "git_repo:",
        "  branch_main: " .. yaml_style(c.blue, { "is_bold" }),
        "  branch_other: " .. yaml_style(c.purple),
        "  git_clean: " .. yaml_style(c.green),
        "  git_dirty: " .. yaml_style(c.red),
        "security_context:",
        "  colon: " .. yaml_style(c.inconspicuous),
        "  user: " .. yaml_style(c.foreground),
        "  role: " .. yaml_style(c.purple),
        "  typ: " .. yaml_style(c.comment),
        "  range: " .. yaml_style(c.violet),
        "file_type:",
        "  image: " .. yaml_style(c.yellow),
        "  video: " .. yaml_style(c.red),
        "  music: " .. yaml_style(c.green),
        "  lossless: " .. yaml_style(c.teal),
        "  crypto: " .. yaml_style(c.orange),
        "  document: " .. yaml_style(c.foreground),
        "  compressed: " .. yaml_style(c.purple),
        "  temp: " .. yaml_style(c.inconspicuous),
        "  compiled: " .. yaml_style(c.violet),
        "  build: " .. yaml_style(c.orange),
        "  source: " .. yaml_style(c.blue),
        "punctuation: " .. yaml_style(c.inconspicuous),
        "date: " .. yaml_style(c.comment),
        "inode: " .. yaml_style(c.inconspicuous),
        "blocks: " .. yaml_style(c.comment),
        "header: " .. yaml_style(c.foreground, { "is_bold" }),
        "octal: " .. yaml_style(c.teal),
        "flags: " .. yaml_style(c.violet),
        "symlink_path: " .. yaml_style(c.teal),
        "control_char: " .. yaml_style(c.orange),
        "broken_symlink: " .. yaml_style(c.red),
        "broken_path_overlay: " .. yaml_style(c.inconspicuous),
    }
    return join(lines)
end

local function bat(theme)
    local c = theme.colors
    local entries = {
        { "Comment", "comment, punctuation.definition.comment", c.comment, "italic" },
        { "String", "string", c.green },
        { "Number and constant", "constant.numeric, constant.language, constant.character", c.yellow },
        { "Escape and special", "constant.character.escape, string.regexp", c.orange },
        { "Keyword", "keyword, storage.modifier", c.purple },
        { "Type", "storage.type, entity.name.type, entity.name.class, support.type", c.red },
        { "Function", "entity.name.function, support.function, meta.function-call", c.blue },
        { "Property", "variable.other.member, support.variable.property", c.violet },
        { "Tag", "entity.name.tag", c.orange },
        { "Markup heading", "markup.heading", c.blue, "bold" },
        { "Markup link", "markup.underline.link", c.teal, "underline" },
        { "Markup inserted", "markup.inserted", c.green },
        { "Markup deleted", "markup.deleted", c.red },
        { "Invalid", "invalid, invalid.illegal", c.red, "bold" },
    }
    local lines = {
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        '<plist version="1.0">',
        "<dict>",
        "  <key>name</key>",
        "  <string>" .. theme.slug .. "</string>",
        "  <key>author</key>",
        "  <string>Nova theme generator</string>",
        "  <key>settings</key>",
        "  <array>",
        "    <dict>",
        "      <key>settings</key>",
        "      <dict>",
        "        <key>background</key><string>" .. c.background .. "</string>",
        "        <key>foreground</key><string>" .. c.foreground .. "</string>",
        "        <key>caret</key><string>" .. c.red .. "</string>",
        "        <key>selection</key><string>" .. c.selection .. "</string>",
        "        <key>lineHighlight</key><string>" .. c.stripline .. "</string>",
        "        <key>invisibles</key><string>" .. c.inconspicuous .. "</string>",
        "      </dict>",
        "    </dict>",
    }
    for _, entry in ipairs(entries) do
        vim.list_extend(lines, {
            "    <dict>",
            "      <key>name</key><string>" .. entry[1] .. "</string>",
            "      <key>scope</key><string>" .. entry[2] .. "</string>",
            "      <key>settings</key>",
            "      <dict>",
            "        <key>foreground</key><string>" .. entry[3] .. "</string>",
        })
        if entry[4] then
            lines[#lines + 1] = "        <key>fontStyle</key><string>" .. entry[4] .. "</string>"
        end
        vim.list_extend(lines, { "      </dict>", "    </dict>" })
    end
    vim.list_extend(lines, { "  </array>", "</dict>", "</plist>" })
    return join(lines)
end

local function delta(theme)
    local c = theme.colors
    local blend = require("nova.utils").blend
    local plus_emph = blend(c.green, c.background, theme.appearance == "light" and 0.16 or 0.35)
    local minus_emph = blend(c.red, c.background, theme.appearance == "light" and 0.16 or 0.35)
    return header("#") .. join({
        string.format('[delta "%s"]', theme.slug),
        "    dark = " .. tostring(theme.appearance == "dark"),
        "    syntax-theme = " .. theme.slug,
        string.format('    minus-style = syntax "%s"', c.diff_delete_bg),
        string.format('    minus-emph-style = syntax "%s"', minus_emph),
        string.format('    plus-style = syntax "%s"', c.diff_add_bg),
        string.format('    plus-emph-style = syntax "%s"', plus_emph),
        "    zero-style = syntax",
        string.format('    commit-style = bold "%s"', c.violet),
        string.format('    file-style = bold "%s"', c.blue),
        string.format('    file-decoration-style = "%s"', c.splitline),
        string.format('    hunk-header-style = syntax "%s"', c.popupmenu),
        string.format('    hunk-header-decoration-style = "%s" box', c.splitline),
        string.format('    line-numbers-minus-style = "%s"', c.red),
        string.format('    line-numbers-zero-style = "%s"', c.inconspicuous),
        string.format('    line-numbers-plus-style = "%s"', c.green),
    })
end

local function starship(theme)
    local c = theme.colors
    local palette_name = theme.slug:gsub("-", "_")
    local values = {
        black = theme.ansi[1],
        red = c.red,
        green = c.green,
        yellow = c.yellow,
        blue = c.blue,
        purple = c.purple,
        cyan = c.teal,
        white = theme.ansi[8],
        orange = c.orange,
        violet = c.violet,
        foreground = c.foreground,
        comment = c.comment,
        muted = c.inconspicuous,
        background = c.background,
        surface = c.stripline,
        selection = c.selection,
        accent = c.target,
    }
    local lines = {
        header("#"):gsub("\n$", ""),
        string.format("palette = %q", palette_name),
        "",
        string.format("[palettes.%s]", palette_name),
    }
    local keys = vim.tbl_keys(values)
    table.sort(keys)
    for _, key in ipairs(keys) do
        lines[#lines + 1] = string.format("%s = %q", key, values[key])
    end
    return join(lines)
end

local function zellij(theme)
    local c = theme.colors
    local lines = {
        header("//"):gsub("\n$", ""),
        "themes {",
        "  " .. theme.slug .. " {",
        string.format('    fg "%s"', c.foreground),
        string.format('    bg "%s"', c.background),
        string.format('    black "%s"', theme.ansi[1]),
        string.format('    red "%s"', theme.ansi[2]),
        string.format('    green "%s"', theme.ansi[3]),
        string.format('    yellow "%s"', theme.ansi[4]),
        string.format('    blue "%s"', theme.ansi[5]),
        string.format('    magenta "%s"', theme.ansi[6]),
        string.format('    cyan "%s"', theme.ansi[7]),
        string.format('    white "%s"', theme.ansi[8]),
        string.format('    orange "%s"', c.orange),
    }

    local function component(name, base, background)
        vim.list_extend(lines, {
            "    " .. name .. " {",
            string.format('      base "%s"', base),
            string.format('      background "%s"', background),
            string.format('      emphasis_0 "%s"', c.orange),
            string.format('      emphasis_1 "%s"', c.teal),
            string.format('      emphasis_2 "%s"', c.violet),
            string.format('      emphasis_3 "%s"', c.purple),
            "    }",
        })
    end

    component("text_unselected", c.foreground, c.background)
    component("text_selected", c.foreground, c.selection)
    component("ribbon_unselected", c.comment, c.popupmenu)
    component("ribbon_selected", c.background, c.blue)
    component("table_title", c.blue, c.background)
    component("table_cell_unselected", c.foreground, c.background)
    component("table_cell_selected", c.foreground, c.selection)
    component("list_unselected", c.foreground, c.background)
    component("list_selected", c.foreground, c.selection)
    component("frame_selected", c.target, c.background)
    component("frame_highlight", c.current_match, c.background)
    component("exit_code_success", c.green, c.background)
    component("exit_code_error", c.red, c.background)

    vim.list_extend(lines, {
        "    multiplayer_user_colors {",
        string.format('      player_1 "%s"', c.red),
        string.format('      player_2 "%s"', c.orange),
        string.format('      player_3 "%s"', c.yellow),
        string.format('      player_4 "%s"', c.green),
        string.format('      player_5 "%s"', c.teal),
        string.format('      player_6 "%s"', c.blue),
        string.format('      player_7 "%s"', c.violet),
        string.format('      player_8 "%s"', c.purple),
        string.format('      player_9 "%s"', c.comment),
        string.format('      player_10 "%s"', c.foreground),
        "    }",
        "  }",
        "}",
    })
    return join(lines)
end

local function lazygit(theme)
    local c = theme.colors
    local function item(value)
        return "      - '" .. value .. "'"
    end
    return header("#") .. join({
        "gui:",
        "  theme:",
        "    activeBorderColor:",
        item(c.target),
        "      - bold",
        "    inactiveBorderColor:",
        item(c.splitline),
        "    searchingActiveBorderColor:",
        item(c.current_match),
        "      - bold",
        "    optionsTextColor:",
        item(c.blue),
        "    selectedLineBgColor:",
        item(c.selection),
        "    inactiveViewSelectedLineBgColor:",
        item(c.stripline),
        "    cherryPickedCommitFgColor:",
        item(c.blue),
        "    cherryPickedCommitBgColor:",
        item(c.popupmenu),
        "    markedBaseCommitFgColor:",
        item(c.background),
        "    markedBaseCommitBgColor:",
        item(c.yellow),
        "    unstagedChangesColor:",
        item(c.red),
        "    defaultFgColor:",
        item(c.foreground),
    })
end

local function palette_export(theme)
    return {
        name = theme.name,
        slug = theme.slug,
        appearance = theme.appearance,
        variant = theme.variant,
        colors = theme.colors,
        ansi = theme.ansi,
        brights = theme.brights,
    }
end

local function write(output, relative, content, files)
    local path = output .. "/" .. relative
    vim.fn.mkdir(vim.fs.dirname(path), "p")
    local normalized = content:gsub("\n+$", "")
    vim.fn.writefile(vim.split(normalized, "\n", { plain = true }), path)
    files[#files + 1] = relative
end

function M.generate(output)
    output = vim.fs.normalize(output)
    vim.fn.mkdir(output, "p")

    local themes = {}
    for _, variant in ipairs(variants) do
        for _, appearance in ipairs(appearances) do
            themes[#themes + 1] = derive(appearance, variant)
        end
    end

    local files = {}
    local windows_schemes = {}
    local palette_data = {}

    for _, theme in ipairs(themes) do
        windows_schemes[#windows_schemes + 1] = windows_terminal(theme)
        palette_data[#palette_data + 1] = palette_export(theme)

        write(output, "wezterm/" .. theme.slug .. ".toml", wezterm(theme), files)
        write(output, "alacritty/" .. theme.slug .. ".toml", alacritty(theme), files)
        write(output, "kitty/" .. theme.slug .. ".conf", kitty(theme), files)
        write(output, "ghostty/" .. theme.slug, ghostty(theme), files)
        write(output, "fzf/" .. theme.slug .. ".sh", fzf(theme), files)
        write(output, "helix/" .. theme.slug:gsub("-", "_") .. ".toml", helix(theme), files)
        write(output, "pi/" .. theme.slug .. ".json", pi_theme(theme), files)
        write(output, "eza/" .. theme.slug .. ".yml", eza(theme), files)
        write(output, "bat/" .. theme.slug .. ".tmTheme", bat(theme), files)
        write(output, "delta/" .. theme.slug .. ".gitconfig", delta(theme), files)
        write(output, "starship/" .. theme.slug .. ".toml", starship(theme), files)
        write(output, "zellij/" .. theme.slug .. ".kdl", zellij(theme), files)
        write(output, "lazygit/" .. theme.slug .. ".yml", lazygit(theme), files)
    end

    write(output, "windows-terminal/nova.json", json_encode({ schemes = windows_schemes }) .. "\n", files)
    write(output, "palettes/nova.json", json_encode({ palettes = palette_data }) .. "\n", files)
    table.sort(files)
    return files
end

return M
